- sudo: yes
  hosts: "{{ hosts }}"  
  vars:
    version: nginx-1.4.1
    install_path: /usr/local/nginx
    src: /tmp
  tasks:
    - name: be sure pcre is installed
      yum: name=pcre-7.8 state=installed

    - name: be sure pcre-devel is installed
      yum: name=pcre-devel-7.8 state=installed

    - get_url: url=http://nginx.org/download/{{ version }}.tar.gz dest={{ src }}
    - command: tar xvfz {{ version }}.tar.gz chdir={{ src }} creates={{ src }}/{{ version }}
    - command: >
        ./configure
        --prefix={{ install_path }}
        --with-http_ssl_module
        --with-http_stub_status_module
        chdir={{ src }}/{{ version }}
    - command: make chdir={{ src }}/{{ version }}
    - command: make install chdir={{ src }}/{{ version }}